### ISSUE TITLE
Capabilities for IPFS + libp2p

### ISSUE THREAD

**Issue by flyingzumwalt** [protocol/lab-week-unconf#17]
lead: @diasdavid 

Goal: 
- define why we need it (use cases)
- define the 3 first milestones

**Comment by lgierth** [comment]
- capabilities: ACLs in a distributed context
- users in dApps sharing data with other users in these dApps, without having their own namespace
- e.g. google docs: there's a mechanism to share the content of a doc
- pedro and david have been looking into how that works: not very clear
- peerpad capability model: share capability key via URL fragment
  - cryptpad
    - single endpoint for content/data
    - no replication of data
  - peerpad
    - signing key
    - read-only mode
  - google docs
    - authentication for read-only / write
- tahoe-lafs
  - least-authoritative filesystem
  - share data by encrypting data with sharee's key
  - can revoke key, then server rejects read requests
  - least authority: share only what you want to share
  - server is choke point that can revoke keys/data and reject access
- why in libp2p/ipfs?
  - important primitive for dApps
- this session
  - identify primitives
  - how far do we need to push for it to become part of libp2p core / ipfs core
- use case
  - dApp with non-public assets, readable only for specific users
  - per-user data, single-user privacy
  - presence of private namespace by default
  - identification, personas
    - be able to recover access
  - multiparty, groups, teams
  - user management
    - metadata
    - user attributes
    - delegation, e.g. oauth
  - how do passwords, 2FA, product tokens look like in a distributed context?
- authentication, authorization, accounting
- porcelain/userland to ipfs core
- current state and next steps
  - figure out the why, and existing options
  - after making building blocks libraries for A/A/A, observe usage patterns
  - write user stories
  - go through academic research
  - possible key result: survey of existing A/A/A research
  - potentially work with existing identity projects (e.g. uPort)
- Q: is this a libp2p protocol/service of relatively static data on IPFS?
  - we don't know yet, we need survey and to observe usage patterns

**Comment by lidel** [comment]
Something I failed to mention during the session, but may be an interesting read related to these areas:
>  - identification, personas
> - user management / delegation
> - how do passwords, 2FA, product tokens look like in a distributed context?
> - authentication

_SQRL protocol_ is a fairly  solid answer to a problem of identity fragmentation. It improves on protocols such as OAuth and OpenID by **not requiring a third party to broker the transaction**, and by **not giving a server any secrets to protect, such as username and password.**

References: 
- [Wikipedia entry](https://en.wikipedia.org/wiki/SQRL)
- [Homepage](http://sqrl.pl)
- [Illustrated guide](http://sqrl.pl/guide/)
- [HTML5DevConf Daniel Holmlund: "Authentication without Passwords Implementing SQRL"](https://youtu.be/WHFaiUc7Qwk) 
   (1h+ Youtube talk by Intel employee)
-  [SQRL: A new method of authentication](http://www.techrepublic.com/blog/it-security/sqrl-a-new-method-of-authentication-with-qr-codes/) (article)
- [Detailed documentation](https://www.grc.com/sqrl/sqrl.htm) (Table of Contents is  at the end of page)
  - []()
